name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]  # Aciona o workflow quando há um push para a branch main
  pull_request:
    branches: [ "main" ]  # Aciona o workflow quando um pull request é aberto para a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install
          mkdir artifacts && cp target/*.jar artifacts
          cd artifacts && ls

      - name: Save artifact
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: github-action-artifact
          path: artifacts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alisson4
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  # Use um secret para a senha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alisson4/spring-boot-github-action-demo:latest  # Use seu nome de usuário

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Mudei de aws-ec2 para ubuntu-latest
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull alisson4/spring-boot-github-action-demo:latest  # Use seu nome de usuário

      - name: Delete old container
        run: |
          if [ "$(docker ps -aq -f name=spring-boot-app-container)" ]; then
            docker rm -f spring-boot-app-container
          fi

      - name: Run Docker Image
        run: |
          docker run -d -p 8080:8080 --name spring-boot-app-container alisson4/spring-boot-github-action-demo:latest  # Use seu nome de usuário
